### ISSUE TITLE
Creates new folder for the life

### ISSUE THREAD

**Issue by obvionaoe** [PeronTheDuck/glob-to-drive#5]
I'm uploading the file to a folder using the folder id, but the action creates a new folder inside that and uploads it into that new folder...

I don't think it should do this, it's kinda misleading

How could I make it so that the new folder does not get created?

Thanks

**Comment by PeronTheDuck** [comment]
Hi, thanks for taking the time to report this! 
One thing to note: if you are uploading a file inside a folder then Glob to Drive will try to create that folder and then upload the file there. Take as an example a file "bar.txt" inside "foo" (`foo/bar.txt`), Glob to Drive will say in the logs "`Uploading 'foo/bar.txt' to 'uploadTo'`" and the resulting file will be `uploadTo/foo/bar.txt`. This is working as intended.
Nevertheless, I thought it would be useful to have an option to control whether or not to create those sub-folders (or to just throw all the files found inside `uploadTo`). Please check v4, which I just published, and see if it suits your needs.

**Comment by obvionaoe** [comment]
Yes, I agree that would be the intended behaviour, but my file is in the root of the repository, it's not inside a folder!

Glob to Drive says in the logs "`Uploading '/bar.txt' to 'uploadTo'`", yet it creates a folder called `New folder` inside `uploadTo`

Your v4 works like a charm though! Thank you very much
